//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrangedRequests
    {
        public int IdArrangedRequests { get; set; }
        public int IdRequest { get; set; }
        public string IdVolunteer { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
