//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HelpForElderlyEntities1 : DbContext
    {
        public HelpForElderlyEntities1()
            : base("name=HelpForElderlyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArrangedRequests> ArrangedRequests { get; set; }
        public virtual DbSet<AskingForHelp> AskingForHelp { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Servic> Servic { get; set; }
        public virtual DbSet<ServiceVolunteer> ServiceVolunteer { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
    
        public virtual ObjectResult<getNextVolunteeringDetails_Result> getNextVolunteeringDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNextVolunteeringDetails_Result>("getNextVolunteeringDetails", idParameter);
        }
    
        public virtual int GetVolunteerHoursInfo(string idVolunteer, ObjectParameter hoursThisMonth, ObjectParameter averageLastMonth)
        {
            var idVolunteerParameter = idVolunteer != null ?
                new ObjectParameter("IdVolunteer", idVolunteer) :
                new ObjectParameter("IdVolunteer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetVolunteerHoursInfo", idVolunteerParameter, hoursThisMonth, averageLastMonth);
        }
    
        public virtual int GetVolunteerMonthlyHours(string idVolunteer, ObjectParameter totalHoursThisMonth, ObjectParameter averageHoursLastMonth)
        {
            var idVolunteerParameter = idVolunteer != null ?
                new ObjectParameter("IdVolunteer", idVolunteer) :
                new ObjectParameter("IdVolunteer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetVolunteerMonthlyHours", idVolunteerParameter, totalHoursThisMonth, averageHoursLastMonth);
        }
    
        public virtual int NumVolunteersForThisServiceAndApproved(Nullable<int> idService, ObjectParameter volunteersCount, ObjectParameter approvedRequestsCount)
        {
            var idServiceParameter = idService.HasValue ?
                new ObjectParameter("IdService", idService) :
                new ObjectParameter("IdService", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NumVolunteersForThisServiceAndApproved", idServiceParameter, volunteersCount, approvedRequestsCount);
        }
    
        public virtual ObjectResult<VolunteersHaveMostHoursToDonateLeft_Result> VolunteersHaveMostHoursToDonateLeft(Nullable<int> idService)
        {
            var idServiceParameter = idService.HasValue ?
                new ObjectParameter("IdService", idService) :
                new ObjectParameter("IdService", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VolunteersHaveMostHoursToDonateLeft_Result>("VolunteersHaveMostHoursToDonateLeft", idServiceParameter);
        }
    }
}
