//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.ArrangedRequests = new HashSet<ArrangedRequests>();
        }
    
        public int IdRequest { get; set; }
        public string IdAskingForHelp { get; set; }
        public string RequestContent { get; set; }
        public string StatusRequest { get; set; }
        public System.DateTime DateRequest { get; set; }
        public int IdService { get; set; }
        public int NumHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArrangedRequests> ArrangedRequests { get; set; }
        public virtual AskingForHelp AskingForHelp { get; set; }
        public virtual Servic Servic { get; set; }
    }
}
