//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceVolunteer
    {
        public int IdServiceVolunteer { get; set; }
        public string IdVolunteer { get; set; }
        public int IdService { get; set; }
        public int HoursVolunteerForMonth { get; set; }
    
        public virtual Servic Servic { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
